/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.clientes;
import modelo.orden;
import modelo.tiquet;

/**
 *
 * @author Usuario
 */
public class EditarOrden extends javax.swing.JFrame {
    
    String idCadOrden = "";
    int idOrden =0;
    tiquet nuevoTiquet = new tiquet();
    orden nuevaOrden = new orden();
    int idCliente = 0;
    clientes nuevoCliente = new clientes();
    

    /**
     * Creates new form EditarOrden
     */
    public EditarOrden() throws SQLException {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setTitle("Calzado Seiya");
        this.setResizable(false);
        this.llenarCB();
        this.llenarCBClientes();
        
    }
    
    public void llenarCB() throws SQLException{
        cmbOrden.removeAllItems(); //Vaciamos el JComboBox
        this.cmbOrden.addItem("Seleccione una Orden");
        ArrayList<String> resultat;
        resultat = nuevoTiquet.CargarCombo();//La consulta tiene que retornar un ArrayList

        for(int i=0; i<resultat.size();i++){
            cmbOrden.addItem(resultat.get(i));
        }
    }
    
    public void llenarCampos() throws SQLException{
        //cmbOrden.removeAllItems(); //Vaciamos el JComboBox
        ArrayList<orden> resultat;
        resultat = nuevaOrden.CargarDatosOrden(idCadOrden);//La consulta tiene que retornar un ArrayList
        int x = 4;
        int idc =0;
        String ciu ="";
        String fecent ="";
        String fecped = "";
        String nom = "";
        for (orden ord : new orden().CargarDatosOrden(idCadOrden)){
                  idc = ord.getCliente();
                  ciu=  ord.getCiudad();
                  fecped = ord.getPedido();
                  fecent = ord.getEntrega();                  
        }
        
        this.ciudad.setText(ciu);
        this.entrge.setText(fecent);
        this.pedido.setText(fecped);
        nom =nuevoCliente.consultarNomCliente(idc); 
        this.cmbClientes.setSelectedItem(nom);
        
    }
    
    public void llenarCBClientes() throws SQLException{
        this.cmbClientes.removeAllItems(); //Vaciamos el JComboBox
        this.cmbClientes.addItem("Seleccione un Cliente");
        ArrayList<String> resultat;
        resultat = this.nuevoCliente.CargarComboCliente();//La consulta tiene que retornar un ArrayList

        for(int i=0; i<resultat.size();i++){
            this.cmbClientes.addItem(resultat.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        pedido = new javax.swing.JTextField();
        entrge = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        cmbOrden = new javax.swing.JComboBox();
        cmbClientes = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Orden"));

        jLabel1.setText("Orden N°");

        jLabel3.setText("Cliente");

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Fecha Pedido:");

        jLabel6.setText("Fecha Entrega");

        Actualizar.setText("Actualizar Orden");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Actualizar)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entrge)
                                    .addComponent(ciudad)
                                    .addComponent(cmbOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pedido)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(109, 109, 109)
                                .addComponent(cmbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(entrge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Actualizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        if(this.idCadOrden.equals("")){
            this.mensaje.setText("Seleccione una Orden");

        }else {

            try {
                String ciudad = this.ciudad.getText();
                String fechaPed = this.pedido.getText();
                String fechaEnt = this.entrge.getText();
               
                boolean con= this.nuevaOrden.actualizarOrden(idCadOrden, idCliente, ciudad, fechaPed, fechaEnt);
                if(con==false)
                this.mensaje.setText("La Orden No se pudo actualizar");
                else{
                    //this.registarOrden();
                    this.mensaje.setText("Orden Actualizada Correctamente");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Generar_Orden.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_ActualizarActionPerformed

    public void registarOrden(){
      // String orden1 =  this.cmbOrden.getSelectedItem().toString();
      // int cliente = Integer.parseInt(this.cliente.getText());
       String ciudad = this.ciudad.getText();
       String pedido = this.pedido.getText();
       String entrega = this.entrge.getText();
       
     //  System.out.print(orden1 + "\n" + idCliente + "\n" + ciudad + "\n" + pedido + "\n" + entrega);
       
     //  nuevaOrden.registrarOrden(orden1, idCliente, ciudad, pedido, entrega);
    }
    
    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        // TODO add your handling code here:
        try {

            idCadOrden = (String) cmbOrden.getSelectedItem();
            idOrden= nuevoTiquet.consultarIdOrden(idCadOrden);
            llenarCampos();
            System.out.print(idCadOrden);

        } catch (SQLException ex) {
            Logger.getLogger(Tiquet.class.getName()).log(Level.SEVERE, null, ex);
            this.mensaje.setText("Error al Cargar tiqued desde la orden");
        }
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        try {
            // TODO add your handling code here:
            String cli = (String) this.cmbClientes.getSelectedItem();
            idCliente= this.nuevoCliente.consultarIdCliente(cli);
        }catch(Exception ex){
            
        }
        //this.mensaje.setText(""+idCliente);
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            llenarCB();
        } catch (SQLException ex) {
            Logger.getLogger(Generar_Orden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Clientes verCliente=new Clientes();

            //línea 2-hacemos visible el formulario que queremos llamar
            verCliente.setVisible(true);
            llenarCB();
        } catch(Exception e){
            System.out.println("Error al abrir la ventana de Cliente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditarOrden().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EditarOrden.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JComboBox cmbClientes;
    private javax.swing.JComboBox cmbOrden;
    private javax.swing.JTextField entrge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField pedido;
    // End of variables declaration//GEN-END:variables
}
