/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.crearPdf;
import modelo.pdf;
import modelo.plantillaPDF;
import modelo.tiquet;
import javax.swing.ImageIcon;
/**
 *
 * @author Usuario
 */
public class Imprimi_Tiquet extends javax.swing.JFrame {

    tiquet nuevoTiquet = new tiquet();
    plantillaPDF nuevoPDF = new plantillaPDF();
    crearPdf xxx=new crearPdf();
    int idOrden =0, tiq =0;
    String idCadOrden = "";
    /**
     * Creates new form Imprimi_Tiquet
     */
    public Imprimi_Tiquet() throws SQLException {
        initComponents();
      //  this.setIconImage(new ImageIcon(getClass().getResource("../Recursos/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setTitle("Calzado Seiya");
        this.setResizable(false);
        llenarCB();
        
    }
    
    public void llenarCB() throws SQLException{
        cmbOrden.removeAllItems(); //Vaciamos el JComboBox
        ArrayList<String> resultat;
        resultat = nuevoTiquet.CargarCombo();//La consulta tiene que retornar un ArrayList

        for(int i=0; i<resultat.size();i++){
            cmbOrden.addItem(resultat.get(i));
        }
    }
    
    public void llenarCmbTiquet(int id) throws SQLException{
        cmbTiquet.removeAllItems(); //Vaciamos el JComboBox
        ArrayList<String> resultat;
        resultat = nuevoTiquet.CargarComboTiquet(id);//La consulta tiene que retornar un ArrayList

        for(int i=0; i<resultat.size();i++){
            cmbTiquet.addItem(resultat.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbOrden = new javax.swing.JComboBox();
        cmbTiquet = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imprimir Tiquet"));

        jLabel1.setText("Seleccione Orden:");

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });

        cmbTiquet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiquetActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione Tiquet:");

        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTiquet, 0, 178, Short.MAX_VALUE)
                                    .addComponent(cmbOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(imprimir)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTiquet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(imprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/seiya curvas_opt.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        try {
            
           idCadOrden = (String) cmbOrden.getSelectedItem();
           idOrden= nuevoTiquet.consultarIdOrden(idCadOrden);   
           
          this.llenarCmbTiquet(idOrden);//llena combo tiquet
       
        
        } catch (SQLException ex) {
            Logger.getLogger(Tiquet.class.getName()).log(Level.SEVERE, null, ex);
            this.mensaje.setText("Error al Cargar tiqued desde la orden");
        }
        
        
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        // TODO add your handling code here:
        String x = (String) this.cmbTiquet.getSelectedItem();
        tiq=Integer.parseInt(x);
        //this.mensaje.setText(""+tiq);
       // this.xxx.pdf(tiq,idOrden, idCadOrden);
       // pdf nn =new pdf();
       // nn.main();
        
        String resp ="";
        try {
            //xxx.ITextHelloWorld();
            resp = this.xxx.pdf(tiq,idOrden, idCadOrden);
            
            if(resp.equals("exito"))
                this.mensaje.setText("PDF generado con Correctamente");
                
        } catch (Exception ex) {
             this.mensaje.setText(resp);
        }
        
        
    }//GEN-LAST:event_imprimirActionPerformed

    private void cmbTiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiquetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTiquetActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOrden;
    private javax.swing.JComboBox cmbTiquet;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
